# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookMyShowAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookMyShowAssignment
  
  pod 'Kingfisher'

  target 'BookMyShowAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookMyShowAssignmentUITests' do
    # Pods for testing
  end

end
